# # -*- coding: utf-8 -*-

# # Form implementation generated from reading ui file 'update.ui'
# #
# # Created by: PyQt5 UI code generator 5.15.10
# #
# # WARNING: Any manual changes made to this file will be lost when pyuic5 is
# # run again.  Do not edit this file unless you know what you are doing.


# from PyQt5 import QtCore, QtGui, QtWidgets
# import sys
# from PyQt5.QtWidgets import QApplication, QMainWindow
# from PyQt5.uic import loadUi

# from selenium.webdriver.chrome.options import Options
# 
# 

# from selenium.webdriver.support import expected_conditions as EC
# from selenium.common.exceptions import TimeoutException, NoSuchElementException
# from datetime import datetime

# import time
# import random
# from pyotp import TOTP





from PyQt5 import QtCore, QtGui, QtWidgets

import sys

#built on top of Selenium WebDriver , provides additional functionalities
#and utilities to simplify web automation tasks.
from seleniumbase import Driver

#allowing you to utilize the power of Selenium WebDriver for automating interactions with web browsers
from selenium import webdriver

#use wait till webpage is actually opened
from selenium.webdriver.support.ui import WebDriverWait 

# (Expected_Conditions) to use the predefined conditions provided by Selenium for explicit waits.
from selenium.webdriver.support import expected_conditions as EC 

#to click icon
from selenium.webdriver.common.keys import Keys 

#allow to use that locate elements on the web page
from selenium.webdriver.common.by import By 

#Exceptions
from selenium.common.exceptions import TimeoutException, NoSuchElementException

#To check password from www.hongpage.com/hongbooking
import requests 

#work with dates and times
from datetime import datetime

#uses it to retrieve the current timestamp
import time

def get_current_password():
    response = requests.get('https://www.hongpage.com/get_password')
    data = response.json()
    return data['password']


#log-in 
def attempt_login(driver, username, password):
    username_field_id = "username"  # Replace with the actual ID of the username field
    password_field_id = "password"  # Replace with the actual ID of the password field
    login_url = "https://auth.42.fr/auth/realms/students-42/protocol/openid-connect/auth?client_id=intra&redirect_uri=https%3A%2F%2Fprofile.intra.42.fr%2Fusers%2Fauth%2Fkeycloak_student%2Fcallback&response_type=code&state=e510170b7adc7ed8fc39319b0c9896692df12a594087df4c"

    driver.get(login_url)
    #time.sleep(1)

    try:
        WebDriverWait(driver, 1).until(EC.element_to_be_clickable((By.ID, username_field_id)))
        username_field = driver.find_element(By.ID, username_field_id)
        username_field.send_keys(username)

        WebDriverWait(driver, 1).until(EC.element_to_be_clickable((By.ID, password_field_id)))
        password_field = driver.find_element(By.ID, password_field_id)
        password_field.send_keys(password)
        password_field.send_keys(Keys.ENTER)
        
        # Wait for navigation and check if the login was successful
        WebDriverWait(driver, 0.5).until(EC.url_to_be("https://profile.intra.42.fr/"))
        #self.statusBar.showMessage("Successfully logged in")
        
        print("Successfully logged in")
        return True  # Return True to indicate successful login

    except Exception as e:
        print("An error occurred:", e)
        return False  # Return False to indicate login failure

#Select time 
def is_valid_time(time_str):
    try:
        datetime.strptime(time_str, "%H:%M")
        return True
    except ValueError:
        return False

def attempt_time(start_time, end_time):
    if is_valid_time(start_time) and is_valid_time(end_time):
        print("Successfully typed desired_eval_time")
        return True
    else:
        print("Invalid time format. Please use HH:MM format.")
        return False

# Function to convert 12-hour format time to 24-hour format
def convert_to_24hr_format(time_str):
    try:
        return datetime.strptime(time_str, "%I:%M %p").strftime("%H:%M")
    except ValueError:
        print(f"Error converting time: {time_str}")
        return None

# Function to check if the slot time is within the desired range
def is_time_within_range(time_str, start_time, end_time):
    try:
        slot_time = datetime.strptime(time_str, "%H:%M").time()  # Expecting 24-hour format
        return start_time <= slot_time <= end_time
    except ValueError as e:
        print(f"Error parsing time: {time_str} - {e}")
        return False




class Ui_MainWindow(object):
    # def __init__(self):
    #     self.driver = webdriver.Chrome()  # Create a Chrome WebDriver instance


    def setupUi(self, MainWindow):
        super().__init__()
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 365)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.username_label = QtWidgets.QLabel(self.centralwidget)
        self.username_label.setGeometry(QtCore.QRect(20, 10, 58, 16))
        self.username_label.setObjectName("username_label")

        self.password_label = QtWidgets.QLabel(self.centralwidget)
        self.password_label.setGeometry(QtCore.QRect(20, 50, 261, 20))
        self.password_label.setObjectName("password_label")

        self.project_label = QtWidgets.QLabel(self.centralwidget)
        self.project_label.setGeometry(QtCore.QRect(20, 110, 58, 16))
        self.project_label.setObjectName("project_label")

        self.start_time_label = QtWidgets.QLabel(self.centralwidget)
        self.start_time_label.setGeometry(QtCore.QRect(20, 170, 111, 16))
        self.start_time_label.setObjectName("start_time_label")
        
        self.end_time_label = QtWidgets.QLabel(self.centralwidget)
        self.end_time_label.setGeometry(QtCore.QRect(20, 240, 111, 16))
        self.end_time_label.setObjectName("end_time_label")

        # self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        # self.pushButton.setGeometry(QtCore.QRect(250, 20, 121, 51))
        # self.pushButton.setObjectName("LoginButton")
        # self.pushButton.setText("Log-in Script")  # Set button text
        # # Connect button click event to a function
        # self.pushButton.clicked.connect(self.login_script)
        # self.username = None

        # self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        # self.pushButton.setGeometry(QtCore.QRect(250, 95, 121, 51))
        # self.pushButton.setObjectName("ProjectButton")
        # self.pushButton.setText("Project Script")  # Set button text
        # # Connect button click event to a function

        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(250, 210, 121, 51))
        self.pushButton.setObjectName("TimeButton")
        self.pushButton.setText("Run Script")  # Set button text
        # Connect button click event to a function
        self.pushButton.clicked.connect(self.run_hongbooking_script)



        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(90, 10, 161, 21))
        self.lineEdit.setObjectName("username_input")

        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(90, 50, 161, 21))
        self.lineEdit_2.setObjectName("password_input")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(90, 90, 161, 61))
        self.listWidget.setObjectName("listWidget")
        
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.listWidget_2 = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_2.setGeometry(QtCore.QRect(150, 160, 51, 71))
        self.listWidget_2.setObjectName("listWidget_2")
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        self.listWidget_3 = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_3.setGeometry(QtCore.QRect(150, 240, 51, 71))
        self.listWidget_3.setObjectName("listWidget_3")
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 24))
        self.menubar.setObjectName("menubar")
        self.menu42 = QtWidgets.QMenu(self.menubar)
        self.menu42.setObjectName("menu42")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionstudent = QtWidgets.QAction(MainWindow)
        self.actionstudent.setObjectName("actionstudent")
        self.actionpisciner = QtWidgets.QAction(MainWindow)
        self.actionpisciner.setObjectName("actionpisciner")
        self.actionexit = QtWidgets.QAction(MainWindow)
        self.actionexit.setObjectName("actionexit")
        self.menu42.addAction(self.actionstudent)
        self.menu42.addAction(self.actionpisciner)
        self.menubar.addAction(self.menu42.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Hongbooking"))
        self.username_label.setText(_translate("MainWindow", "ID"))
        self.password_label.setText(_translate("MainWindow", "Password"))
        self.project_label.setText(_translate("MainWindow", "Project"))
        self.start_time_label.setText(_translate("MainWindow", "Desired start time"))
        self.end_time_label.setText(_translate("MainWindow", "Desired end time"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("MainWindow", "c-piscine-bsq"))
        item = self.listWidget.item(1)
        item.setText(_translate("MainWindow", "c-piscine-shell-00"))
        item = self.listWidget.item(2)
        item.setText(_translate("MainWindow", "c-piscine-shell-01"))
        item = self.listWidget.item(3)
        item.setText(_translate("MainWindow", "c-piscine-c-00"))
        item = self.listWidget.item(4)
        item.setText(_translate("MainWindow", "c-piscine-c-01"))
        item = self.listWidget.item(5)
        item.setText(_translate("MainWindow", "c-piscine-c-02"))
        item = self.listWidget.item(6)
        item.setText(_translate("MainWindow", "c-piscine-c-03"))
        item = self.listWidget.item(7)
        item.setText(_translate("MainWindow", "c-piscine-c-04"))
        item = self.listWidget.item(8)
        item.setText(_translate("MainWindow", "c-piscine-c-05"))
        item = self.listWidget.item(9)
        item.setText(_translate("MainWindow", "c-piscine-c-06"))
        item = self.listWidget.item(10)
        item.setText(_translate("MainWindow", "c-piscine-c-07"))
        item = self.listWidget.item(11)
        item.setText(_translate("MainWindow", "c-piscine-c-08"))
        item = self.listWidget.item(12)
        item.setText(_translate("MainWindow", "c-piscine-c-09"))
        item = self.listWidget.item(13)
        item.setText(_translate("MainWindow", "c-piscine-c-10"))
        item = self.listWidget.item(14)
        item.setText(_translate("MainWindow", "c-piscine-c-11"))
        item = self.listWidget.item(15)
        item.setText(_translate("MainWindow", "c-piscine-c-12"))
        item = self.listWidget.item(16)
        item.setText(_translate("MainWindow", "c-piscine-c-13"))
        item = self.listWidget.item(17)
        item.setText(_translate("MainWindow", "42cursus-libft"))
        item = self.listWidget.item(18)
        item.setText(_translate("MainWindow", "42cursus-ft_printf"))
        item = self.listWidget.item(19)
        item.setText(_translate("MainWindow", "42cursus-get_next_line"))
        item = self.listWidget.item(20)
        item.setText(_translate("MainWindow", "born2beroot"))
        item = self.listWidget.item(21)
        item.setText(_translate("MainWindow", "so_long"))
        item = self.listWidget.item(22)
        item.setText(_translate("MainWindow", "42cursus-fdf"))
        item = self.listWidget.item(23)
        item.setText(_translate("MainWindow", "42cursus-fract-ol"))
        item = self.listWidget.item(24)
        item.setText(_translate("MainWindow", "42cursus-push_swap"))
        item = self.listWidget.item(25)
        item.setText(_translate("MainWindow", "minitalk"))
        item = self.listWidget.item(26)
        item.setText(_translate("MainWindow", "pipex"))
        item = self.listWidget.item(27)
        item.setText(_translate("MainWindow", "42cursus-philosophers"))
        item = self.listWidget.item(28)
        item.setText(_translate("MainWindow", "42cursus-minishell"))
        item = self.listWidget.item(29)
        item.setText(_translate("MainWindow", "minirt"))
        item = self.listWidget.item(30)
        item.setText(_translate("MainWindow", "cub3d"))
        item = self.listWidget.item(31)
        item.setText(_translate("MainWindow", "netpractice"))
        item = self.listWidget.item(32)
        item.setText(_translate("MainWindow", "inception"))
        item = self.listWidget.item(33)
        item.setText(_translate("MainWindow", "webserv"))
        item = self.listWidget.item(34)
        item.setText(_translate("MainWindow", "ft_irc"))
        item = self.listWidget.item(35)
        item.setText(_translate("MainWindow", "cpp-module-00"))
        item = self.listWidget.item(36)
        item.setText(_translate("MainWindow", "cpp-module-01"))
        item = self.listWidget.item(37)
        item.setText(_translate("MainWindow", "cpp-module-02"))
        item = self.listWidget.item(38)
        item.setText(_translate("MainWindow", "cpp-module-03"))
        item = self.listWidget.item(39)
        item.setText(_translate("MainWindow", "cpp-module-04"))
        item = self.listWidget.item(40)
        item.setText(_translate("MainWindow", "cpp-module-05"))
        item = self.listWidget.item(41)
        item.setText(_translate("MainWindow", "cpp-module-06"))
        item = self.listWidget.item(42)
        item.setText(_translate("MainWindow", "cpp-module-07"))
        item = self.listWidget.item(43)
        item.setText(_translate("MainWindow", "cpp-module-08"))
        item = self.listWidget.item(44)
        item.setText(_translate("MainWindow", "cpp-module-09"))
        item = self.listWidget.item(45)
        item.setText(_translate("MainWindow", "ft_transcendence"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.listWidget_2.isSortingEnabled()
        self.listWidget_2.setSortingEnabled(False)
        item = self.listWidget_2.item(0)
        item.setText(_translate("MainWindow", "00:00"))
        item = self.listWidget_2.item(1)
        item.setText(_translate("MainWindow", "00:15"))
        item = self.listWidget_2.item(2)
        item.setText(_translate("MainWindow", "00:30"))
        item = self.listWidget_2.item(3)
        item.setText(_translate("MainWindow", "00:45"))
        item = self.listWidget_2.item(4)
        item.setText(_translate("MainWindow", "01:00"))
        item = self.listWidget_2.item(5)
        item.setText(_translate("MainWindow", "01:15"))
        item = self.listWidget_2.item(6)
        item.setText(_translate("MainWindow", "01:30"))
        item = self.listWidget_2.item(7)
        item.setText(_translate("MainWindow", "01:45"))
        item = self.listWidget_2.item(8)
        item.setText(_translate("MainWindow", "02:00"))
        item = self.listWidget_2.item(9)
        item.setText(_translate("MainWindow", "02:15"))
        item = self.listWidget_2.item(10)
        item.setText(_translate("MainWindow", "02:30"))
        item = self.listWidget_2.item(11)
        item.setText(_translate("MainWindow", "02:45"))
        item = self.listWidget_2.item(12)
        item.setText(_translate("MainWindow", "03:00"))
        item = self.listWidget_2.item(13)
        item.setText(_translate("MainWindow", "03:15"))
        item = self.listWidget_2.item(14)
        item.setText(_translate("MainWindow", "03:30"))
        item = self.listWidget_2.item(15)
        item.setText(_translate("MainWindow", "03:45"))
        item = self.listWidget_2.item(16)
        item.setText(_translate("MainWindow", "04:00"))
        item = self.listWidget_2.item(17)
        item.setText(_translate("MainWindow", "04:15"))
        item = self.listWidget_2.item(18)
        item.setText(_translate("MainWindow", "04:30"))
        item = self.listWidget_2.item(19)
        item.setText(_translate("MainWindow", "04:45"))
        item = self.listWidget_2.item(20)
        item.setText(_translate("MainWindow", "05:00"))
        item = self.listWidget_2.item(21)
        item.setText(_translate("MainWindow", "05:15"))
        item = self.listWidget_2.item(22)
        item.setText(_translate("MainWindow", "05:30"))
        item = self.listWidget_2.item(23)
        item.setText(_translate("MainWindow", "05:45"))
        item = self.listWidget_2.item(24)
        item.setText(_translate("MainWindow", "06:00"))
        item = self.listWidget_2.item(25)
        item.setText(_translate("MainWindow", "06:15"))
        item = self.listWidget_2.item(26)
        item.setText(_translate("MainWindow", "06:30"))
        item = self.listWidget_2.item(27)
        item.setText(_translate("MainWindow", "06:45"))
        item = self.listWidget_2.item(28)
        item.setText(_translate("MainWindow", "07:00"))
        item = self.listWidget_2.item(29)
        item.setText(_translate("MainWindow", "07:15"))
        item = self.listWidget_2.item(30)
        item.setText(_translate("MainWindow", "07:30"))
        item = self.listWidget_2.item(31)
        item.setText(_translate("MainWindow", "07:45"))
        item = self.listWidget_2.item(32)
        item.setText(_translate("MainWindow", "08:00"))
        item = self.listWidget_2.item(33)
        item.setText(_translate("MainWindow", "08:15"))
        item = self.listWidget_2.item(34)
        item.setText(_translate("MainWindow", "08:30"))
        item = self.listWidget_2.item(35)
        item.setText(_translate("MainWindow", "08:45"))
        item = self.listWidget_2.item(36)
        item.setText(_translate("MainWindow", "09:00"))
        item = self.listWidget_2.item(37)
        item.setText(_translate("MainWindow", "09:15"))
        item = self.listWidget_2.item(38)
        item.setText(_translate("MainWindow", "09:30"))
        item = self.listWidget_2.item(39)
        item.setText(_translate("MainWindow", "09:45"))
        item = self.listWidget_2.item(40)
        item.setText(_translate("MainWindow", "10:00"))
        item = self.listWidget_2.item(41)
        item.setText(_translate("MainWindow", "10:15"))
        item = self.listWidget_2.item(42)
        item.setText(_translate("MainWindow", "10:30"))
        item = self.listWidget_2.item(43)
        item.setText(_translate("MainWindow", "10:45"))
        item = self.listWidget_2.item(44)
        item.setText(_translate("MainWindow", "11:00"))
        item = self.listWidget_2.item(45)
        item.setText(_translate("MainWindow", "11:15"))
        item = self.listWidget_2.item(46)
        item.setText(_translate("MainWindow", "11:30"))
        item = self.listWidget_2.item(47)
        item.setText(_translate("MainWindow", "11:45"))
        item = self.listWidget_2.item(48)
        item.setText(_translate("MainWindow", "12:00"))
        item = self.listWidget_2.item(49)
        item.setText(_translate("MainWindow", "12:15"))
        item = self.listWidget_2.item(50)
        item.setText(_translate("MainWindow", "12:30"))
        item = self.listWidget_2.item(51)
        item.setText(_translate("MainWindow", "12:45"))
        item = self.listWidget_2.item(52)
        item.setText(_translate("MainWindow", "13:00"))
        item = self.listWidget_2.item(53)
        item.setText(_translate("MainWindow", "13:15"))
        item = self.listWidget_2.item(54)
        item.setText(_translate("MainWindow", "13:30"))
        item = self.listWidget_2.item(55)
        item.setText(_translate("MainWindow", "13:45"))
        item = self.listWidget_2.item(56)
        item.setText(_translate("MainWindow", "14:00"))
        item = self.listWidget_2.item(57)
        item.setText(_translate("MainWindow", "14:15"))
        item = self.listWidget_2.item(58)
        item.setText(_translate("MainWindow", "14:30"))
        item = self.listWidget_2.item(59)
        item.setText(_translate("MainWindow", "14:45"))
        item = self.listWidget_2.item(60)
        item.setText(_translate("MainWindow", "15:00"))
        item = self.listWidget_2.item(61)
        item.setText(_translate("MainWindow", "15:15"))
        item = self.listWidget_2.item(62)
        item.setText(_translate("MainWindow", "15:30"))
        item = self.listWidget_2.item(63)
        item.setText(_translate("MainWindow", "15:45"))
        item = self.listWidget_2.item(64)
        item.setText(_translate("MainWindow", "16:00"))
        item = self.listWidget_2.item(65)
        item.setText(_translate("MainWindow", "16:15"))
        item = self.listWidget_2.item(66)
        item.setText(_translate("MainWindow", "16:30"))
        item = self.listWidget_2.item(67)
        item.setText(_translate("MainWindow", "16:45"))
        item = self.listWidget_2.item(68)
        item.setText(_translate("MainWindow", "17:00"))
        item = self.listWidget_2.item(69)
        item.setText(_translate("MainWindow", "17:15"))
        item = self.listWidget_2.item(70)
        item.setText(_translate("MainWindow", "17:30"))
        item = self.listWidget_2.item(71)
        item.setText(_translate("MainWindow", "17:45"))
        item = self.listWidget_2.item(72)
        item.setText(_translate("MainWindow", "18:00"))
        item = self.listWidget_2.item(73)
        item.setText(_translate("MainWindow", "18:15"))
        item = self.listWidget_2.item(74)
        item.setText(_translate("MainWindow", "18:30"))
        item = self.listWidget_2.item(75)
        item.setText(_translate("MainWindow", "18:45"))
        item = self.listWidget_2.item(76)
        item.setText(_translate("MainWindow", "19:00"))
        item = self.listWidget_2.item(77)
        item.setText(_translate("MainWindow", "19:15"))
        item = self.listWidget_2.item(78)
        item.setText(_translate("MainWindow", "19:30"))
        item = self.listWidget_2.item(79)
        item.setText(_translate("MainWindow", "19:45"))
        item = self.listWidget_2.item(80)
        item.setText(_translate("MainWindow", "20:00"))
        item = self.listWidget_2.item(81)
        item.setText(_translate("MainWindow", "20:15"))
        item = self.listWidget_2.item(82)
        item.setText(_translate("MainWindow", "20:30"))
        item = self.listWidget_2.item(83)
        item.setText(_translate("MainWindow", "20:45"))
        item = self.listWidget_2.item(84)
        item.setText(_translate("MainWindow", "21:00"))
        item = self.listWidget_2.item(85)
        item.setText(_translate("MainWindow", "21:15"))
        item = self.listWidget_2.item(86)
        item.setText(_translate("MainWindow", "21:30"))
        item = self.listWidget_2.item(87)
        item.setText(_translate("MainWindow", "21:45"))
        item = self.listWidget_2.item(88)
        item.setText(_translate("MainWindow", "22:00"))
        item = self.listWidget_2.item(89)
        item.setText(_translate("MainWindow", "22:15"))
        item = self.listWidget_2.item(90)
        item.setText(_translate("MainWindow", "22:30"))
        item = self.listWidget_2.item(91)
        item.setText(_translate("MainWindow", "22:45"))
        item = self.listWidget_2.item(92)
        item.setText(_translate("MainWindow", "23:00"))
        item = self.listWidget_2.item(93)
        item.setText(_translate("MainWindow", "23:15"))
        item = self.listWidget_2.item(94)
        item.setText(_translate("MainWindow", "23:30"))
        item = self.listWidget_2.item(95)
        item.setText(_translate("MainWindow", "23:45"))
        item = self.listWidget_2.item(96)
        item.setText(_translate("MainWindow", "23:59"))
        self.listWidget_2.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.listWidget_3.isSortingEnabled()
        self.listWidget_3.setSortingEnabled(False)
        item = self.listWidget_3.item(0)
        item.setText(_translate("MainWindow", "00:00"))
        item = self.listWidget_3.item(1)
        item.setText(_translate("MainWindow", "00:15"))
        item = self.listWidget_3.item(2)
        item.setText(_translate("MainWindow", "00:30"))
        item = self.listWidget_3.item(3)
        item.setText(_translate("MainWindow", "00:45"))
        item = self.listWidget_3.item(4)
        item.setText(_translate("MainWindow", "01:00"))
        item = self.listWidget_3.item(5)
        item.setText(_translate("MainWindow", "01:15"))
        item = self.listWidget_3.item(6)
        item.setText(_translate("MainWindow", "01:30"))
        item = self.listWidget_3.item(7)
        item.setText(_translate("MainWindow", "01:45"))
        item = self.listWidget_3.item(8)
        item.setText(_translate("MainWindow", "02:00"))
        item = self.listWidget_3.item(9)
        item.setText(_translate("MainWindow", "02:15"))
        item = self.listWidget_3.item(10)
        item.setText(_translate("MainWindow", "02:30"))
        item = self.listWidget_3.item(11)
        item.setText(_translate("MainWindow", "02:45"))
        item = self.listWidget_3.item(12)
        item.setText(_translate("MainWindow", "03:00"))
        item = self.listWidget_3.item(13)
        item.setText(_translate("MainWindow", "03:15"))
        item = self.listWidget_3.item(14)
        item.setText(_translate("MainWindow", "03:30"))
        item = self.listWidget_3.item(15)
        item.setText(_translate("MainWindow", "03:45"))
        item = self.listWidget_3.item(16)
        item.setText(_translate("MainWindow", "04:00"))
        item = self.listWidget_3.item(17)
        item.setText(_translate("MainWindow", "04:15"))
        item = self.listWidget_3.item(18)
        item.setText(_translate("MainWindow", "04:30"))
        item = self.listWidget_3.item(19)
        item.setText(_translate("MainWindow", "04:45"))
        item = self.listWidget_3.item(20)
        item.setText(_translate("MainWindow", "05:00"))
        item = self.listWidget_3.item(21)
        item.setText(_translate("MainWindow", "05:15"))
        item = self.listWidget_3.item(22)
        item.setText(_translate("MainWindow", "05:30"))
        item = self.listWidget_3.item(23)
        item.setText(_translate("MainWindow", "05:45"))
        item = self.listWidget_3.item(24)
        item.setText(_translate("MainWindow", "06:00"))
        item = self.listWidget_3.item(25)
        item.setText(_translate("MainWindow", "06:15"))
        item = self.listWidget_3.item(26)
        item.setText(_translate("MainWindow", "06:30"))
        item = self.listWidget_3.item(27)
        item.setText(_translate("MainWindow", "06:45"))
        item = self.listWidget_3.item(28)
        item.setText(_translate("MainWindow", "07:00"))
        item = self.listWidget_3.item(29)
        item.setText(_translate("MainWindow", "07:15"))
        item = self.listWidget_3.item(30)
        item.setText(_translate("MainWindow", "07:30"))
        item = self.listWidget_3.item(31)
        item.setText(_translate("MainWindow", "07:45"))
        item = self.listWidget_3.item(32)
        item.setText(_translate("MainWindow", "08:00"))
        item = self.listWidget_3.item(33)
        item.setText(_translate("MainWindow", "08:15"))
        item = self.listWidget_3.item(34)
        item.setText(_translate("MainWindow", "08:30"))
        item = self.listWidget_3.item(35)
        item.setText(_translate("MainWindow", "08:45"))
        item = self.listWidget_3.item(36)
        item.setText(_translate("MainWindow", "09:00"))
        item = self.listWidget_3.item(37)
        item.setText(_translate("MainWindow", "09:15"))
        item = self.listWidget_3.item(38)
        item.setText(_translate("MainWindow", "09:30"))
        item = self.listWidget_3.item(39)
        item.setText(_translate("MainWindow", "09:45"))
        item = self.listWidget_3.item(40)
        item.setText(_translate("MainWindow", "10:00"))
        item = self.listWidget_3.item(41)
        item.setText(_translate("MainWindow", "10:15"))
        item = self.listWidget_3.item(42)
        item.setText(_translate("MainWindow", "10:30"))
        item = self.listWidget_3.item(43)
        item.setText(_translate("MainWindow", "10:45"))
        item = self.listWidget_3.item(44)
        item.setText(_translate("MainWindow", "11:00"))
        item = self.listWidget_3.item(45)
        item.setText(_translate("MainWindow", "11:15"))
        item = self.listWidget_3.item(46)
        item.setText(_translate("MainWindow", "11:30"))
        item = self.listWidget_3.item(47)
        item.setText(_translate("MainWindow", "11:45"))
        item = self.listWidget_3.item(48)
        item.setText(_translate("MainWindow", "12:00"))
        item = self.listWidget_3.item(49)
        item.setText(_translate("MainWindow", "12:15"))
        item = self.listWidget_3.item(50)
        item.setText(_translate("MainWindow", "12:30"))
        item = self.listWidget_3.item(51)
        item.setText(_translate("MainWindow", "12:45"))
        item = self.listWidget_3.item(52)
        item.setText(_translate("MainWindow", "13:00"))
        item = self.listWidget_3.item(53)
        item.setText(_translate("MainWindow", "13:15"))
        item = self.listWidget_3.item(54)
        item.setText(_translate("MainWindow", "13:30"))
        item = self.listWidget_3.item(55)
        item.setText(_translate("MainWindow", "13:45"))
        item = self.listWidget_3.item(56)
        item.setText(_translate("MainWindow", "14:00"))
        item = self.listWidget_3.item(57)
        item.setText(_translate("MainWindow", "14:15"))
        item = self.listWidget_3.item(58)
        item.setText(_translate("MainWindow", "14:30"))
        item = self.listWidget_3.item(59)
        item.setText(_translate("MainWindow", "14:45"))
        item = self.listWidget_3.item(60)
        item.setText(_translate("MainWindow", "15:00"))
        item = self.listWidget_3.item(61)
        item.setText(_translate("MainWindow", "15:15"))
        item = self.listWidget_3.item(62)
        item.setText(_translate("MainWindow", "15:30"))
        item = self.listWidget_3.item(63)
        item.setText(_translate("MainWindow", "15:45"))
        item = self.listWidget_3.item(64)
        item.setText(_translate("MainWindow", "16:00"))
        item = self.listWidget_3.item(65)
        item.setText(_translate("MainWindow", "16:15"))
        item = self.listWidget_3.item(66)
        item.setText(_translate("MainWindow", "16:30"))
        item = self.listWidget_3.item(67)
        item.setText(_translate("MainWindow", "16:45"))
        item = self.listWidget_3.item(68)
        item.setText(_translate("MainWindow", "17:00"))
        item = self.listWidget_3.item(69)
        item.setText(_translate("MainWindow", "17:15"))
        item = self.listWidget_3.item(70)
        item.setText(_translate("MainWindow", "17:30"))
        item = self.listWidget_3.item(71)
        item.setText(_translate("MainWindow", "17:45"))
        item = self.listWidget_3.item(72)
        item.setText(_translate("MainWindow", "18:00"))
        item = self.listWidget_3.item(73)
        item.setText(_translate("MainWindow", "18:15"))
        item = self.listWidget_3.item(74)
        item.setText(_translate("MainWindow", "18:30"))
        item = self.listWidget_3.item(75)
        item.setText(_translate("MainWindow", "18:45"))
        item = self.listWidget_3.item(76)
        item.setText(_translate("MainWindow", "19:00"))
        item = self.listWidget_3.item(77)
        item.setText(_translate("MainWindow", "19:15"))
        item = self.listWidget_3.item(78)
        item.setText(_translate("MainWindow", "19:30"))
        item = self.listWidget_3.item(79)
        item.setText(_translate("MainWindow", "19:45"))
        item = self.listWidget_3.item(80)
        item.setText(_translate("MainWindow", "20:00"))
        item = self.listWidget_3.item(81)
        item.setText(_translate("MainWindow", "20:15"))
        item = self.listWidget_3.item(82)
        item.setText(_translate("MainWindow", "20:30"))
        item = self.listWidget_3.item(83)
        item.setText(_translate("MainWindow", "20:45"))
        item = self.listWidget_3.item(84)
        item.setText(_translate("MainWindow", "21:00"))
        item = self.listWidget_3.item(85)
        item.setText(_translate("MainWindow", "21:15"))
        item = self.listWidget_3.item(86)
        item.setText(_translate("MainWindow", "21:30"))
        item = self.listWidget_3.item(87)
        item.setText(_translate("MainWindow", "21:45"))
        item = self.listWidget_3.item(88)
        item.setText(_translate("MainWindow", "22:00"))
        item = self.listWidget_3.item(89)
        item.setText(_translate("MainWindow", "22:15"))
        item = self.listWidget_3.item(90)
        item.setText(_translate("MainWindow", "22:30"))
        item = self.listWidget_3.item(91)
        item.setText(_translate("MainWindow", "22:45"))
        item = self.listWidget_3.item(92)
        item.setText(_translate("MainWindow", "23:00"))
        item = self.listWidget_3.item(93)
        item.setText(_translate("MainWindow", "23:15"))
        item = self.listWidget_3.item(94)
        item.setText(_translate("MainWindow", "23:30"))
        item = self.listWidget_3.item(95)
        item.setText(_translate("MainWindow", "23:45"))
        item = self.listWidget_3.item(96)
        item.setText(_translate("MainWindow", "23:59"))
        self.listWidget_3.setSortingEnabled(__sortingEnabled)
        self.menu42.setTitle(_translate("MainWindow", "42"))
        self.actionstudent.setText(_translate("MainWindow", "student"))
        self.actionpisciner.setText(_translate("MainWindow", "pisciner"))
        self.actionexit.setText(_translate("MainWindow", "exit"))
        
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        MainWindow.setStatusBar(self.statusBar)
        
        # Initially, show a message on the status bar
        # self.statusBar.showMessage("Ready")
        self.statusBar.showMessage("Once you click 'pushbutton', Hongbooking will automatically book an evaluation slot")

    def run_hongbooking_script(self):
        # Retrieve input values
        # username = self.lineEdit.text()
        # password = self.lineEdit_2.text()
        #project_name = self.listWidget
        username = self.lineEdit.text()
        password = self.lineEdit_2.text()
        project_name = self.listWidget.currentItem().text()
        start_time = self.listWidget_2.currentItem().text()
        end_time = self.listWidget_3.currentItem().text()

        # Print or use input values
        print("Username:", username)
        # print("Password:", password)
        print("Project Name:", project_name)
        print("Start Time:", start_time)
        print("End Time:", end_time)

        #options = uc.ChromeOptions()
        #localhost_number = random.randint(65536, 65999)
        #options.add_experimental_option("debuggerAddress", f"localhost:{localhost_number}")    
        #chromedriver_path = '/home/hongbaki/bin/chromedriver'
        #driver = uc.Chrome(driver_executable_path=chromedriver_path ,options=options)        
        #driver = Driver(uc=True, incognito=True)
        # options.add_argument("--headless")
        
        driver = Driver(uc=True)
        print("Let's book an evaluation slot automatically")

        # Continue with the rest of your script after a successful login
        logged_in = False
        while not logged_in:
            logged_in = attempt_login(driver, username, password)
            if not logged_in:
                # self.statusBar.showMessage("Login failed. Please try again.")
                print("Login failed. Please try again.")
                sys.exit(app.exec_())
        
        
        # Dynamically build the URL
        base_url = "https://projects.intra.42.fr/projects"
        full_url = f"{base_url}/{project_name}/slots?team_id=True"
        # Navigate to the specified slots page
        driver.get(full_url)
        int_evaluation_day = 0

        time_in = False
        while not time_in:
            time_in = attempt_time(start_time, end_time)
            if not time_in:
                print("time has not typed. Please try again.")

        # Set the desired time for the slot
        desired_start_time = datetime.strptime(start_time, "%H:%M").time()  # 24-hour format
        desired_end_time = datetime.strptime(end_time, "%H:%M").time()  # 24-hour format


        # This flag will indicate whether a slot has been successfully clicked
        slot_clicked = False
        attempts = 0
        program_start_time = time.time()  # Get the current time in seconds
        previous_elapsed_time = time.time() - program_start_time - 1
        
        time_min_is_60 = 60
        ###################################################
        #################################################
        time_for_min = 20 #20min
        #################################################
        ###################################################
        setting_time = time_for_min * time_min_is_60 

        while not slot_clicked:
            elapsed_time = time.time() - program_start_time
            if elapsed_time > setting_time:
                
                print("Reached the " , setting_time ,"min. Exiting.")

                driver.quit()  # Close the WebDriver
                sys.exit()  # Terminate the program
            
            # Add code here to handle the situation when elapsed_time is not getting smaller
            if elapsed_time <= previous_elapsed_time:
                print("Elapsed time is not decreasing. Taking necessary action...")
                driver.quit()  # Close the WebDriver
                sys.exit()  # Terminate the program
                
            previous_elapsed_time = elapsed_time
            
            
            try:
            
                attempts += 1
                print(f"{attempts}, booking attempt")
                #self.statusBar.showMessage(f"{attempts}, booking attempt")

                # self.statusBar.showMessage(f"Hongbooking will stop running in {round(elapsed_time)}/1200 seconds")


                time.sleep(1)

                try:         
                    available_slots_today = []                      
                    current_day = datetime.now().weekday()
                    xpath = f".//tr/td[{current_day + 2 + int_evaluation_day}]//div[contains(@class, 'fc-time')]"
                    slots = driver.find_elements(By.XPATH, xpath)
                    if (len(slots) == 0):
                        driver.refresh()
                    print("Every 20 min, new password will be regenerated")
                    #print("New password is here")
                    #print("www.hongpage.com/hongbooking")
                    int_elapsed_time = int(elapsed_time)
                    print(f"Hongbooking will stop running in {(round((int_elapsed_time) / 60))}/20 mins")
                    # Create a new QStatusBar object
                    #statusBar = QtWidgets.QStatusBar()
                    # Set the status bar for the main window
                    #MainWindow.setStatusBar(statusBar)

                    #statusBar.showMessage(f"Hongbooking will stop running in {round(int_elapsed_time) / 60} seconds / 20 mins")

                    
                    



                    for slot in slots:
                        print("there is another available slot", slot.text)
                        time_str = slot.get_attribute("data-full").split(" - ")[0]
                        # Debugging: Check the type and value of time_str
                        #print("21 : time_str:", time_str, "Type:", type(time_str))

                        if is_time_within_range(convert_to_24hr_format(time_str), desired_start_time, desired_end_time):
                            available_slots_today.append(slot)

                    if not available_slots_today:
                        print("No slots available within the desired time range.")
                        driver.refresh()
                        time.sleep(1)
                        continue
                    

                    for slot in available_slots_today:

                        WebDriverWait(driver, 10).until(EC.element_to_be_clickable(slot))
                        
                        #EC.element_to_be_clickable(slot)

                        slot.click()
                        print("Clicked on an available slot.")
                        slot_clicked = True
                        
                        
                        # Find the "OK" button. Adjust the selector as per your page's structure
                        try:
                            nextok = driver.find_element(By.CSS_SELECTOR, "button.btn.btn-primary")
                            WebDriverWait(driver, 10).until(EC.element_to_be_clickable(nextok))
                            if nextok.text == "OK":
                                
                                
                                print("BEFORE: Clicking 'OK' button.")
                                nextok.click()
                                print("AFTER: Clicked 'OK' button.")
                        except NoSuchElementException:
                            print("OK button not found.")
        
                        #break

                except NoSuchElementException:
                    print("Today's column is not found or not highlighted.")
                    driver.refresh()
                    time.sleep(1)

            except TimeoutException:
                print("Timeout occurred while looking for slots. Refreshing and retrying...")
                driver.refresh()
            except Exception as e:
                print(f"An unexpected error occurred: {e}")
                break

        #time.sleep(50)
        # Close the WebDriver
        #8.Close the WebDriver:
        #This line closes the browser and ends the WebDriver's session. 
        # It's important to include this to free up resources and not leave the browser running in the background.
        driver.quit()


        # Ensure proper indentation and alignment
        # Modify the script as needed to integrate with your GUI
        # Make sure to replace any print statements with methods to update the GUI
        
        # Existing script goes here

        # Make sure to replace print statements with methods to update the GUI
        #self.statusBar().showMessage("Running Hongbooking script...")
        # Example of updating a label text
        # self.label.setText("Script is running...")
        # Example of showing message box
        # QMessageBox.information(self, "Information", "Script is running...")
        # Example of showing message in status bar
        # self.statusBar().showMessage("Running Hongbooking script...")
        # Example of updating list widget
        # self.listWidget.addItem("New item added")
        # Ensure to handle exceptions properly and display error messages to the user


# if __name__ == "__main__":
#     # # get password from www.hongpage.com/hongbooking
#     # correct_password = get_current_password()
    
#     # # Password should be typed as an argument
#     # if len(sys.argv) < 2:
#     #     print("Error: No password provided. Please run the script with the correct password as an argument.")
#     #     print("You can find password www.hongpage.com/hongbooking")
#     #     sys.exit(app.exec_())
#     # entered_password = sys.argv[1]

#     # # if password is not correct
#     # if entered_password != correct_password:
#     #     print("Error: Incorrect password. Access denied.")
#     #     sys.exit(app.exec_())


#     # If the correct password is entered, continue with your program logic
#     print("Access granted. Running the program...")
#     app = QtWidgets.QApplication(sys.argv)
#     MainWindow = QtWidgets.QMainWindow()
#     ui = Ui_MainWindow()
#     ui.setupUi(MainWindow)
#     MainWindow.show()
#     sys.exit(app.exec_())


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
            
    # Get password from the user
    # Prompt the user for password and display a reference
    entered_password, ok = QtWidgets.QInputDialog.getText(None, "Enter Password", 
                                                        "Please enter the password:\n\n"
                                                        "New password is here\n"
                                                        "www.hongpage.com/hongbooking")

    if ok:
        # Check if the entered password is correct
        correct_password = get_current_password()  # Assuming you have a function to retrieve the correct password
        
        if entered_password == correct_password:
            # If the correct password is entered, continue with your program logic
            print("Access granted. Running the program...")
            MainWindow = QtWidgets.QMainWindow()
            ui = Ui_MainWindow()
            ui.setupUi(MainWindow)
            MainWindow.show()
            sys.exit(app.exec_())
        else:
            print("Error: Incorrect password. Access denied.")
            #QtWidgets.QInputDialog.getText(None, "Password Incorrect", "Error: Incorrect password. Access denied.")
             # If the password is incorrect, display an error message dialog
            msgBox = QtWidgets.QMessageBox()
            msgBox.setIcon(QtWidgets.QMessageBox.Warning)
            msgBox.setText("Error: Incorrect password. Access denied.")
            msgBox.setWindowTitle("Password Incorrect")
            msgBox.setStandardButtons(QtWidgets.QMessageBox.Ok)
            returnValue = msgBox.exec_()
            if returnValue == QtWidgets.QMessageBox.Ok:
                # Handle OK button clicked
                pass
    else:
        print("Error: Password input canceled. Access denied.")

